### ISSUE TITLE
#9 Chrome unresponsive when switching out of edit mode in large Boards (i.e. Microsoft)

### ISSUE THREAD

**Issue by matthewc100** [DellISG/Klue_issues#11]
Switch in/out of edit mode -> Chrome unresponsive. This appears to be happening specifically on very image-heavy Boards. Investigation is still ongoing as to what is causing it. Only visible to Curators who are switching into edit mode. Fix in the works but will take time (not a quick fix). Eric welcome to demo issue to recreate issue and look through logs if it will help.

**Comment by ndoliveira2016** [comment]
Interesting note: Clearing cache (or restart) + log in -> Can help

**Comment by matthewc100** [comment]
Yeah, we continue to wonder if it’s some Dell has done to us

Matthew Coblentz 

Sent from a phone with autocorrect.   Please excuse any errors or typos

Envoyé à partir d'un téléphone avec une correction automatique. Excusez toute erreur ou erreur de frappe.

**Comment by ndoliveira2016** [comment]
Matt and the Dell folks are testing this one further to ensure it's still an issue.
