### ISSUE TITLE
Ability to add a table of contents card to make content more easy to access

### ISSUE THREAD

**Issue by matthewc100** [DellISG/Klue_issues#14]
see also anchor text requests

**Comment by ndoliveira2016** [comment]
Neil - New Board UI works, but if it's coming later in 2019, ideally we'd have a solution in advance to then

**Comment by ndoliveira2016** [comment]
@matthewc100 Is this one still necessary given that we have the TOC now?

**Comment by ndoliveira2016** [comment]
Curious if we can close this one
