### ISSUE TITLE
Ability to track usage of the Klue Review

### ISSUE THREAD

**Issue by matthewc100** [DellISG/Klue_issues#28]
Open-rate, Clickthrough rate.  Need to embed a tracking cookie or have access to the HTML

**Comment by ndoliveira2016** [comment]
@matthewc100 We have the # of Opens in the Data Studio report (3rd page).
![screen shot 2018-12-06 at 1 37 16 pm](https://user-images.githubusercontent.com/16674211/49613296-23ef6880-f95c-11e8-9f46-ef89a9c0fe57.png)

-> https://datastudio.google.com/u/0/reporting/10j0FlrklFTOgXC5vvX3Q6RnfM6Pv2by4/page/jMMd

We're working towards Open-rate (Unique Opens as a % of users)
