### ISSUE TITLE
Drag "scratchpad" items straight to card

### ISSUE THREAD

**Issue by matthewc100** [DellISG/Klue_issues#36]
Scratchpad is not heavily used but we could encourage more usage if this enhancement existed.

**Comment by ndoliveira2016** [comment]
@matthewc100 This one is possible currently if I understand the issue. See GIF below
![add scratchpad items to profile](https://user-images.githubusercontent.com/16674211/49613049-577dc300-f95b-11e8-9a29-4226475c80b8.gif)

Full help guide on Scratchpad -> https://help.klue.com/sending-content-into-klue/what-is-the-scratchpad-and-how-do-i-use-it
