### ISSUE TITLE
Intel Digest @daily resends previously seen articles

### ISSUE THREAD

**Issue by matthewc100** [DellISG/Klue_issues#50]
The digest sends you every story that's been added to the digest in total, every day.
 
Day 1: Story A & B
Day 2: Story A, B, C & D
Day 3: Story A, B, C, D, E, F & G
Etc, etc
Come Thursday, you receive the same one everyone else does.
It basically sends you everything that's currently sitting in the weekly digest queue every day.

**Comment by matthewc100** [comment]
@ndoliveira2016 says that the current thinking is to remove the Daily option.

**Comment by ndoliveira2016** [comment]
Customization options (daily, weekly, monthly, etc) for individual users have been removed. (caused more harm them good).

Company-wide settings only :)
